# Generated by Django 3.1.6 on 2021-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signup_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_url', models.URLField(max_length=500)),
                ('auth_username', models.CharField(max_length=200)),
                ('auth_password', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='token',
        ),
        migrations.AddField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='signup_request',
            name='displayName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='signup_request',
            name='host',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
